-- Schéma + RLS pour le signalement d'état des salles.
-- À exécuter dans la console SQL Supabase. Idempotent : peut être ré-exécuté.

-- ============================================
-- 1. Tables
-- ============================================

create table if not exists public.salle_etats (
  id          bigint generated by default as identity primary key,
  id_salle    bigint not null references public.salles(id) on delete cascade,
  id_user     uuid   not null references public.profiles(id),
  type        smallint not null,
  commentaire text,
  created_at  timestamptz not null default now()
);

create index if not exists salle_etats_id_salle_idx
  on public.salle_etats (id_salle, created_at desc);

create table if not exists public.salle_etat_photos (
  id         bigint generated by default as identity primary key,
  id_etat    bigint not null references public.salle_etats(id) on delete cascade,
  path       text   not null,
  created_at timestamptz not null default now()
);

create index if not exists salle_etat_photos_id_etat_idx
  on public.salle_etat_photos (id_etat);

-- ============================================
-- 2. RLS sur salle_etats
-- ============================================

alter table public.salle_etats enable row level security;

drop policy if exists "salle_etats_select" on public.salle_etats;
create policy "salle_etats_select"
  on public.salle_etats for select
  to authenticated
  using (true);

drop policy if exists "salle_etats_insert" on public.salle_etats;
create policy "salle_etats_insert"
  on public.salle_etats for insert
  to authenticated
  with check (id_user = auth.uid());

drop policy if exists "salle_etats_delete" on public.salle_etats;
create policy "salle_etats_delete"
  on public.salle_etats for delete
  to authenticated
  using (
    id_user = auth.uid()
    or exists (
      select 1
      from public.profiles p
      join public.salles s on s.id_secteur = p.secteur_admin
      where p.id = auth.uid()
        and s.id = salle_etats.id_salle
    )
  );

-- ============================================
-- 3. RLS sur salle_etat_photos
-- ============================================

alter table public.salle_etat_photos enable row level security;

drop policy if exists "salle_etat_photos_select" on public.salle_etat_photos;
create policy "salle_etat_photos_select"
  on public.salle_etat_photos for select
  to authenticated
  using (true);

drop policy if exists "salle_etat_photos_insert" on public.salle_etat_photos;
create policy "salle_etat_photos_insert"
  on public.salle_etat_photos for insert
  to authenticated
  with check (
    exists (
      select 1 from public.salle_etats e
      where e.id = salle_etat_photos.id_etat
        and e.id_user = auth.uid()
    )
  );

drop policy if exists "salle_etat_photos_delete" on public.salle_etat_photos;
create policy "salle_etat_photos_delete"
  on public.salle_etat_photos for delete
  to authenticated
  using (
    exists (
      select 1 from public.salle_etats e
      where e.id = salle_etat_photos.id_etat
        and (
          e.id_user = auth.uid()
          or exists (
            select 1
            from public.profiles p
            join public.salles s on s.id_secteur = p.secteur_admin
            where p.id = auth.uid()
              and s.id = e.id_salle
          )
        )
    )
  );

-- ============================================
-- 4. Bucket Storage + policies
-- ============================================

insert into storage.buckets (id, name, public)
values ('salle-etats', 'salle-etats', false)
on conflict (id) do update set public = excluded.public;

drop policy if exists "salle_etats_storage_select" on storage.objects;
create policy "salle_etats_storage_select"
  on storage.objects for select
  to authenticated
  using (bucket_id = 'salle-etats');

drop policy if exists "salle_etats_storage_insert" on storage.objects;
create policy "salle_etats_storage_insert"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'salle-etats');

drop policy if exists "salle_etats_storage_delete" on storage.objects;
create policy "salle_etats_storage_delete"
  on storage.objects for delete
  to authenticated
  using (
    bucket_id = 'salle-etats'
    and (
      owner = auth.uid()
      or exists (
        select 1 from public.profiles p
        where p.id = auth.uid() and p.secteur_admin is not null
      )
    )
  );
