-- Schéma + RLS pour le signalement d'état des véhicules.
-- À exécuter dans la console SQL Supabase. Idempotent : peut être ré-exécuté.

-- ============================================
-- 1. Tables
-- ============================================

create table if not exists public.vehicule_etats (
  id          bigint generated by default as identity primary key,
  id_vehicule bigint not null references public.vehicules(id) on delete cascade,
  id_user     uuid   not null references public.profiles(id),
  type        smallint not null,
  commentaire text,
  created_at  timestamptz not null default now()
);

create index if not exists vehicule_etats_id_vehicule_idx
  on public.vehicule_etats (id_vehicule, created_at desc);

create table if not exists public.vehicule_etat_photos (
  id         bigint generated by default as identity primary key,
  id_etat    bigint not null references public.vehicule_etats(id) on delete cascade,
  path       text   not null,
  created_at timestamptz not null default now()
);

create index if not exists vehicule_etat_photos_id_etat_idx
  on public.vehicule_etat_photos (id_etat);

-- ============================================
-- 2. RLS sur vehicule_etats
-- ============================================

alter table public.vehicule_etats enable row level security;

drop policy if exists "vehicule_etats_select" on public.vehicule_etats;
create policy "vehicule_etats_select"
  on public.vehicule_etats for select
  to authenticated
  using (true);

drop policy if exists "vehicule_etats_insert" on public.vehicule_etats;
create policy "vehicule_etats_insert"
  on public.vehicule_etats for insert
  to authenticated
  with check (id_user = auth.uid());

drop policy if exists "vehicule_etats_delete" on public.vehicule_etats;
create policy "vehicule_etats_delete"
  on public.vehicule_etats for delete
  to authenticated
  using (
    id_user = auth.uid()
    or exists (
      select 1
      from public.profiles p
      join public.vehicules v on v.id_secteur = p.secteur_admin
      where p.id = auth.uid()
        and v.id = vehicule_etats.id_vehicule
    )
  );

-- ============================================
-- 3. RLS sur vehicule_etat_photos
-- ============================================

alter table public.vehicule_etat_photos enable row level security;

drop policy if exists "vehicule_etat_photos_select" on public.vehicule_etat_photos;
create policy "vehicule_etat_photos_select"
  on public.vehicule_etat_photos for select
  to authenticated
  using (true);

drop policy if exists "vehicule_etat_photos_insert" on public.vehicule_etat_photos;
create policy "vehicule_etat_photos_insert"
  on public.vehicule_etat_photos for insert
  to authenticated
  with check (
    exists (
      select 1 from public.vehicule_etats e
      where e.id = vehicule_etat_photos.id_etat
        and e.id_user = auth.uid()
    )
  );

drop policy if exists "vehicule_etat_photos_delete" on public.vehicule_etat_photos;
create policy "vehicule_etat_photos_delete"
  on public.vehicule_etat_photos for delete
  to authenticated
  using (
    exists (
      select 1 from public.vehicule_etats e
      where e.id = vehicule_etat_photos.id_etat
        and (
          e.id_user = auth.uid()
          or exists (
            select 1
            from public.profiles p
            join public.vehicules v on v.id_secteur = p.secteur_admin
            where p.id = auth.uid()
              and v.id = e.id_vehicule
          )
        )
    )
  );

-- ============================================
-- 4. Bucket Storage + policies
-- ============================================

insert into storage.buckets (id, name, public)
values ('vehicule-etats', 'vehicule-etats', false)
on conflict (id) do update set public = excluded.public;

drop policy if exists "vehicule_etats_storage_select" on storage.objects;
create policy "vehicule_etats_storage_select"
  on storage.objects for select
  to authenticated
  using (bucket_id = 'vehicule-etats');

drop policy if exists "vehicule_etats_storage_insert" on storage.objects;
create policy "vehicule_etats_storage_insert"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'vehicule-etats');

drop policy if exists "vehicule_etats_storage_delete" on storage.objects;
create policy "vehicule_etats_storage_delete"
  on storage.objects for delete
  to authenticated
  using (
    bucket_id = 'vehicule-etats'
    and (
      owner = auth.uid()
      or exists (
        select 1 from public.profiles p
        where p.id = auth.uid() and p.secteur_admin is not null
      )
    )
  );
