create table "public"."salles" (
    "id" bigint generated by default as identity not null,
    "is_dispo" smallint not null,
    "name" text,
    "id_secteur" bigint,
    "wifi" smallint,
    "jabra" smallint,
    "clim" smallint,
    "white_board" smallint,
    "pmr" smallint,
    "adresse" text,
    "autres" text
);


alter table "public"."salles" enable row level security;

create table "public"."vehicules" (
    "id" bigint generated by default as identity not null,
    "is_dispo" smallint not null,
    "id_secteur" bigint,
    "carburant" text,
    "carmillon" smallint,
    "capacite" bigint,
    "immat" text,
    "marque" text,
    "model" text,
    "autres" text
);


alter table "public"."vehicules" enable row level security;

alter table "public"."profiles" drop column "id_secteur";

CREATE UNIQUE INDEX salles_pkey ON public.salles USING btree (id);

CREATE UNIQUE INDEX vehicules_pkey ON public.vehicules USING btree (id);

alter table "public"."salles" add constraint "salles_pkey" PRIMARY KEY using index "salles_pkey";

alter table "public"."vehicules" add constraint "vehicules_pkey" PRIMARY KEY using index "vehicules_pkey";

alter table "public"."salles" add constraint "public_salles_id_secteur_fkey" FOREIGN KEY (id_secteur) REFERENCES secteurs(id) not valid;

alter table "public"."salles" validate constraint "public_salles_id_secteur_fkey";

alter table "public"."vehicules" add constraint "public_vehicules_id_secteur_fkey" FOREIGN KEY (id_secteur) REFERENCES secteurs(id) not valid;

alter table "public"."vehicules" validate constraint "public_vehicules_id_secteur_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$begin
  insert into public.profiles (id, email, nom, prenom)
  values (new.id, new.email, new.raw_user_meta_data ->>'nom', new.raw_user_meta_data ->>'prenom');
  return new;
end;$function$
;

grant delete on table "public"."salles" to "anon";

grant insert on table "public"."salles" to "anon";

grant references on table "public"."salles" to "anon";

grant select on table "public"."salles" to "anon";

grant trigger on table "public"."salles" to "anon";

grant truncate on table "public"."salles" to "anon";

grant update on table "public"."salles" to "anon";

grant delete on table "public"."salles" to "authenticated";

grant insert on table "public"."salles" to "authenticated";

grant references on table "public"."salles" to "authenticated";

grant select on table "public"."salles" to "authenticated";

grant trigger on table "public"."salles" to "authenticated";

grant truncate on table "public"."salles" to "authenticated";

grant update on table "public"."salles" to "authenticated";

grant delete on table "public"."salles" to "service_role";

grant insert on table "public"."salles" to "service_role";

grant references on table "public"."salles" to "service_role";

grant select on table "public"."salles" to "service_role";

grant trigger on table "public"."salles" to "service_role";

grant truncate on table "public"."salles" to "service_role";

grant update on table "public"."salles" to "service_role";

grant delete on table "public"."vehicules" to "anon";

grant insert on table "public"."vehicules" to "anon";

grant references on table "public"."vehicules" to "anon";

grant select on table "public"."vehicules" to "anon";

grant trigger on table "public"."vehicules" to "anon";

grant truncate on table "public"."vehicules" to "anon";

grant update on table "public"."vehicules" to "anon";

grant delete on table "public"."vehicules" to "authenticated";

grant insert on table "public"."vehicules" to "authenticated";

grant references on table "public"."vehicules" to "authenticated";

grant select on table "public"."vehicules" to "authenticated";

grant trigger on table "public"."vehicules" to "authenticated";

grant truncate on table "public"."vehicules" to "authenticated";

grant update on table "public"."vehicules" to "authenticated";

grant delete on table "public"."vehicules" to "service_role";

grant insert on table "public"."vehicules" to "service_role";

grant references on table "public"."vehicules" to "service_role";

grant select on table "public"."vehicules" to "service_role";

grant trigger on table "public"."vehicules" to "service_role";

grant truncate on table "public"."vehicules" to "service_role";

grant update on table "public"."vehicules" to "service_role";