create table "public"."carburant" (
    "id" bigint generated by default as identity not null,
    "name" text not null
);


alter table "public"."carburant" enable row level security;

alter table "public"."vehicules" drop column "carburant";

alter table "public"."vehicules" add column "id_carburant" smallint;

CREATE UNIQUE INDEX carburant_pkey ON public.carburant USING btree (id);

alter table "public"."carburant" add constraint "carburant_pkey" PRIMARY KEY using index "carburant_pkey";

alter table "public"."vehicules" add constraint "public_vehicules_id_carburant_fkey" FOREIGN KEY (id_carburant) REFERENCES carburant(id) not valid;

alter table "public"."vehicules" validate constraint "public_vehicules_id_carburant_fkey";

grant delete on table "public"."carburant" to "anon";

grant insert on table "public"."carburant" to "anon";

grant references on table "public"."carburant" to "anon";

grant select on table "public"."carburant" to "anon";

grant trigger on table "public"."carburant" to "anon";

grant truncate on table "public"."carburant" to "anon";

grant update on table "public"."carburant" to "anon";

grant delete on table "public"."carburant" to "authenticated";

grant insert on table "public"."carburant" to "authenticated";

grant references on table "public"."carburant" to "authenticated";

grant select on table "public"."carburant" to "authenticated";

grant trigger on table "public"."carburant" to "authenticated";

grant truncate on table "public"."carburant" to "authenticated";

grant update on table "public"."carburant" to "authenticated";

grant delete on table "public"."carburant" to "service_role";

grant insert on table "public"."carburant" to "service_role";

grant references on table "public"."carburant" to "service_role";

grant select on table "public"."carburant" to "service_role";

grant trigger on table "public"."carburant" to "service_role";

grant truncate on table "public"."carburant" to "service_role";

grant update on table "public"."carburant" to "service_role";