create table "public"."anomalies" (
    "id" bigint generated by default as identity not null,
    "type" smallint not null,
    "id_salle" bigint,
    "id_vehicule" bigint,
    "anomalie" text
);


alter table "public"."anomalies" enable row level security;

alter table "public"."secteurs" add column "superviseurs" text;

CREATE UNIQUE INDEX anomalies_pkey ON public.anomalies USING btree (id);

alter table "public"."anomalies" add constraint "anomalies_pkey" PRIMARY KEY using index "anomalies_pkey";

alter table "public"."anomalies" add constraint "public_anomalies_id_salle_fkey" FOREIGN KEY (id_salle) REFERENCES salles(id) not valid;

alter table "public"."anomalies" validate constraint "public_anomalies_id_salle_fkey";

alter table "public"."anomalies" add constraint "public_anomalies_id_vehicule_fkey" FOREIGN KEY (id_vehicule) REFERENCES vehicules(id) not valid;

alter table "public"."anomalies" validate constraint "public_anomalies_id_vehicule_fkey";

grant delete on table "public"."anomalies" to "anon";

grant insert on table "public"."anomalies" to "anon";

grant references on table "public"."anomalies" to "anon";

grant select on table "public"."anomalies" to "anon";

grant trigger on table "public"."anomalies" to "anon";

grant truncate on table "public"."anomalies" to "anon";

grant update on table "public"."anomalies" to "anon";

grant delete on table "public"."anomalies" to "authenticated";

grant insert on table "public"."anomalies" to "authenticated";

grant references on table "public"."anomalies" to "authenticated";

grant select on table "public"."anomalies" to "authenticated";

grant trigger on table "public"."anomalies" to "authenticated";

grant truncate on table "public"."anomalies" to "authenticated";

grant update on table "public"."anomalies" to "authenticated";

grant delete on table "public"."anomalies" to "service_role";

grant insert on table "public"."anomalies" to "service_role";

grant references on table "public"."anomalies" to "service_role";

grant select on table "public"."anomalies" to "service_role";

grant trigger on table "public"."anomalies" to "service_role";

grant truncate on table "public"."anomalies" to "service_role";

grant update on table "public"."anomalies" to "service_role";

create policy "AllAuthenticated"
on "public"."anomalies"
as permissive
for all
to authenticated
using (true);