create table "public"."resa_salles" (
    "id" bigint generated by default as identity not null,
    "id_salle" bigint not null,
    "id_user" uuid,
    "debut" text,
    "fin" text,
    "is_validated" smallint
);


alter table "public"."resa_salles" enable row level security;

create table "public"."resa_vehicules" (
    "id" bigint generated by default as identity not null,
    "id_vehicule" bigint not null,
    "id_user" uuid,
    "debut" text,
    "fin" text,
    "is_validated" smallint
);


alter table "public"."resa_vehicules" enable row level security;

CREATE UNIQUE INDEX resa_salles_pkey ON public.resa_salles USING btree (id);

CREATE UNIQUE INDEX resa_vehicules_pkey ON public.resa_vehicules USING btree (id);

alter table "public"."resa_salles" add constraint "resa_salles_pkey" PRIMARY KEY using index "resa_salles_pkey";

alter table "public"."resa_vehicules" add constraint "resa_vehicules_pkey" PRIMARY KEY using index "resa_vehicules_pkey";

alter table "public"."resa_salles" add constraint "public_resa_salles_id_salle_fkey" FOREIGN KEY (id_salle) REFERENCES salles(id) ON DELETE CASCADE not valid;

alter table "public"."resa_salles" validate constraint "public_resa_salles_id_salle_fkey";

alter table "public"."resa_salles" add constraint "public_resa_salles_id_user_fkey" FOREIGN KEY (id_user) REFERENCES profiles(id) ON DELETE CASCADE not valid;

alter table "public"."resa_salles" validate constraint "public_resa_salles_id_user_fkey";

alter table "public"."resa_vehicules" add constraint "public_resa_vehicules_id_user_fkey" FOREIGN KEY (id_user) REFERENCES profiles(id) ON DELETE CASCADE not valid;

alter table "public"."resa_vehicules" validate constraint "public_resa_vehicules_id_user_fkey";

alter table "public"."resa_vehicules" add constraint "public_resa_vehicules_id_vehicule_fkey" FOREIGN KEY (id_vehicule) REFERENCES vehicules(id) ON DELETE CASCADE not valid;

alter table "public"."resa_vehicules" validate constraint "public_resa_vehicules_id_vehicule_fkey";

grant delete on table "public"."resa_salles" to "anon";

grant insert on table "public"."resa_salles" to "anon";

grant references on table "public"."resa_salles" to "anon";

grant select on table "public"."resa_salles" to "anon";

grant trigger on table "public"."resa_salles" to "anon";

grant truncate on table "public"."resa_salles" to "anon";

grant update on table "public"."resa_salles" to "anon";

grant delete on table "public"."resa_salles" to "authenticated";

grant insert on table "public"."resa_salles" to "authenticated";

grant references on table "public"."resa_salles" to "authenticated";

grant select on table "public"."resa_salles" to "authenticated";

grant trigger on table "public"."resa_salles" to "authenticated";

grant truncate on table "public"."resa_salles" to "authenticated";

grant update on table "public"."resa_salles" to "authenticated";

grant delete on table "public"."resa_salles" to "service_role";

grant insert on table "public"."resa_salles" to "service_role";

grant references on table "public"."resa_salles" to "service_role";

grant select on table "public"."resa_salles" to "service_role";

grant trigger on table "public"."resa_salles" to "service_role";

grant truncate on table "public"."resa_salles" to "service_role";

grant update on table "public"."resa_salles" to "service_role";

grant delete on table "public"."resa_vehicules" to "anon";

grant insert on table "public"."resa_vehicules" to "anon";

grant references on table "public"."resa_vehicules" to "anon";

grant select on table "public"."resa_vehicules" to "anon";

grant trigger on table "public"."resa_vehicules" to "anon";

grant truncate on table "public"."resa_vehicules" to "anon";

grant update on table "public"."resa_vehicules" to "anon";

grant delete on table "public"."resa_vehicules" to "authenticated";

grant insert on table "public"."resa_vehicules" to "authenticated";

grant references on table "public"."resa_vehicules" to "authenticated";

grant select on table "public"."resa_vehicules" to "authenticated";

grant trigger on table "public"."resa_vehicules" to "authenticated";

grant truncate on table "public"."resa_vehicules" to "authenticated";

grant update on table "public"."resa_vehicules" to "authenticated";

grant delete on table "public"."resa_vehicules" to "service_role";

grant insert on table "public"."resa_vehicules" to "service_role";

grant references on table "public"."resa_vehicules" to "service_role";

grant select on table "public"."resa_vehicules" to "service_role";

grant trigger on table "public"."resa_vehicules" to "service_role";

grant truncate on table "public"."resa_vehicules" to "service_role";

grant update on table "public"."resa_vehicules" to "service_role";
